name: create preprod release tag
on:
  pull_request:
    types: [ labeled ]

jobs:
  create-tag:
    if: ${{ github.event.label.name == 'deploy preprod' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Approved Status
        uses: ./.github/workflows/approved-event

      - name: Get Latest PreProd Release
        id: version
        uses: ./.github/workflows/get-latest-release
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
          view_top: 1

      - name: Bump release version
        id: bump_version
        uses: ./.github/workflows/increment-semantic-version
        with:
          version: '${{ steps.version.outputs.tag_name }}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{  steps.bump_version.outputs.incremented_version }}
          release_name: ${{  steps.bump_version.outputs.incremented_version }}
          draft: false
          prerelease: true