name: create preprod release tag
on:
  pull_request:
    types: [ labeled ]

jobs:
  create-tag:
    if: ${{ github.event.label.name == 'deploy preprod' }}
    # if: contains( ${{ github.event.comment.body }}, )
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest PreProd Release
        id: version
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
          view_top: 1
         
        # uses: pozetroninc/github-action-get-latest-release@master
        # with:
        #   repo: '$${{ github.repository }}'
        #   excludes: release, draft
      - name: "Print result"
        run: |
          echo "token: ${{ github.token }}"
          echo "id: ${{ steps.version.outputs.id }}"
          echo "name: ${{ steps.version.outputs.name }}"
          echo "tag_name: ${{ steps.version.outputs.tag_name }}"
          echo "created_at: ${{ steps.version.outputs.created_atd }}"
          echo "draft: ${{ steps.version.outputs.draft }}"
          echo "prerelease: ${{ steps.version.outputs.prerelease }}"

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: '${{ steps.version.outputs.tag_name }}'
          version-fragment: 'rc'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.next-version }}
          release_name: ${{ steps.bump_version.outputs.next-version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true